SELECT ?name ?human
WHERE{
	SELECT ?human ?name
	WHERE {?event rdf:type dbo:OlympicEvent{?event dbo:bronzeMedalist ?human. ?human dbo:birthPlace ?place . ?place foaf:name ?name } 
	UNION {?event dbo:silverMedalist ?human . ?human dbo:birthPlace ?place . ?place foaf:name ?name} 
	UNION {?event dbo:goldMedalist ?human . ?human dbo:birthPlace ?place . ?place foaf:name ?name}
	FILTER regex(?human, "Michael_Phelps")
	FILTER (lang(?name) = 'en')}
	GROUP BY ?human}
