SELECT ?abstract
WHERE{
	SELECT ?abstract
	WHERE {?event rdf:type dbo:OlympicEvent{?event dbo:bronzeMedalist ?human. ?human dbo:abstract ?abstract } 
	UNION {?event dbo:silverMedalist ?human . ?human dbo:abstract ?abstract } 
	UNION {?event dbo:goldMedalist ?human . ?human dbo:abstract ?abstract }
	FILTER regex(?human, %ATHLETE%)
        FILTER (lang(?abstract) = 'en')}
	GROUP BY ?human}
