SELECT ?weight/1000
WHERE{
	SELECT ?weight ?human
	WHERE {?event rdf:type dbo:OlympicEvent{?event dbo:bronzeMedalist ?human. ?human dbo:weight ?weight } 
	UNION {?event dbo:silverMedalist ?human . ?human dbo:weight ?weight } 
	UNION {?event dbo:goldMedalist ?human . ?human dbo:weight ?weight }
	FILTER regex(?human, %ATHLETE%)}
	GROUP BY ?human}
